services:
  app:
    build: .
    ports:
      - "8085:8085"
    env_file: .env
    depends_on:
      - db
    entrypoint: ["/bin/sh", "-c", "/app/run-migrations.sh && /app/server"]

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: DB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
